[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments/" }]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
monadDevnet = "https://rpc-devnet.monadinfra.com/rpc/3fe540e310bbb6ef0b9f16cd23073b0a"
